#!/usr/bin/env python3
"""
Alternative implementations to replace broken Annoy
generated by Claude 3.5 haiku due to...C++ compiler issues
locally? maybe? 
"""

import numpy as np
from sklearn.neighbors import NearestNeighbors
import pickle

class SklearnAnnoyReplacement:
    """Drop-in replacement for AnnoyIndex using sklearn"""

    def __init__(self, f, metric='cosine'):
        self.f = f
        self.metric = metric if metric != 'angular' else 'cosine'  # angular -> cosine
        self.items = {}
        self.vectors = []
        self.built = False
        self.nn_model = None

    def add_item(self, i, vector):
        """Add item to index"""
        self.items[i] = np.array(vector)

    def build(self, n_trees):
        """Build the index"""
        if not self.items:
            return

        # Convert to matrix
        max_idx = max(self.items.keys())
        self.vectors = np.zeros((max_idx + 1, self.f))

        for idx, vector in self.items.items():
            self.vectors[idx] = vector

        # Build sklearn model
        self.nn_model = NearestNeighbors(
            metric=self.metric,
            algorithm='auto'
        )
        self.nn_model.fit(self.vectors)
        self.built = True

    def get_nns_by_item(self, item_idx, n, search_k=-1):
        """Get nearest neighbors of item"""
        if not self.built:
            raise ValueError("Index not built yet")

        query_vector = self.vectors[item_idx:item_idx+1]  # Keep 2D shape
        distances, indices = self.nn_model.kneighbors(query_vector, n_neighbors=n)
        return indices[0].tolist()

    def get_n_items(self):
        """Get number of items in index"""
        return len(self.vectors) if self.built else len(self.items)

    def save(self, filepath):
        """Save index to file"""
        with open(filepath, 'wb') as f:
            pickle.dump({
                'f': self.f,
                'metric': self.metric,
                'vectors': self.vectors,
                'built': self.built
            }, f)

    def load(self, filepath):
        """Load index from file"""
        with open(filepath, 'rb') as f:
            data = pickle.load(f)

        self.f = data['f']
        self.metric = data['metric']
        self.vectors = data['vectors']
        self.built = data['built']

        if self.built:
            self.nn_model = NearestNeighbors(
                metric=self.metric,
                algorithm='auto'
            )
            self.nn_model.fit(self.vectors)
